### ISSUE TITLE
Add more partitioning schemes for quicksort/quickselect

### ISSUE THREAD

**Issue by piater** [RodrigoDLPontes/visualization-tool#116]
I implemented [Lomuto's partition scheme](https://en.wikipedia.org/wiki/Quicksort#Lomuto_partition_scheme) for my own needs, hard-coding the pivot to the last element, because it is the simplest to write down, explain, and analyze. Currently it only lives on my local system in a separate `helperLomuto()` function.

 Let me know if you're interested; if not, just close this feature request :-).

**Comment by grant-hollosi** [comment]
We would absolutely be interested in that feature! Feel free to open an PR and I'll take a look
