### ISSUE TITLE
Add pseudocode to every visualization

### ISSUE THREAD

**Issue by grant-hollosi** [RodrigoDLPontes/visualization-tool#127]
Each visualization needs to have pseudocode displayed next to the main algorithm/structure. Eventually, each line should also be highlighted when the corresponding operation is being visualized.

List of pages currently implemented with pseudocode/highlighting:
- ArrayList
- Doubly LinkedList
- Circularly LinkedList
- Stack (Array)
- Queue (Array)
- Queue (LinkedList)
- Deque (Array)
- LCS
- HeapSort
- Stack (LinkedList)
- BST 
- Bubble Sort
- Cocktail Shaker Sort
- Insertion Sort
- Selection Sort
- QuickSort
- QuickSelect
- MergeSort
- LSD Radix Sort
-  Brute Force
- Boyer-Moore
- KMP
- Rabin-Karp
- BFS
- DFS
- Dijkstra's
- Prim's
- Kruskal's

Pages that still need pseudocode (priority algos **bolded**):

- Singly LinkedList
- Deque (LinkedList)
- Heap
- AVL
- 2-4 Tree (?)
- SplayTree (?)
- SkipList (?)
- HashMap (Probing)
- HashMap (Chaining)
- Floyd-Warshall (?)

**Comment by luciankt** [comment]
Nearly complete, will treat the last few pages as separate issues
