### ISSUE TITLE
Error in pseudocode for the cocktail shaker sort?

### ISSUE THREAD

**Issue by SCheekati** [RodrigoDLPontes/visualization-tool#165]
![image](https://user-images.githubusercontent.com/88806457/159139436-ef79e475-7f10-4ad4-9407-aa06343bd73b.png)

I think the pseudocode should say swap array[i] with array[i - 1] instead of array[i +1] in the marked section above ^.

[Link] https://csvistool.com/CocktailSort

**Comment by ljones315** [comment]
Thanks for pointing this out!
