### ISSUE TITLE
Visual Bug on main screen

### ISSUE THREAD

**Issue by iWatger** [RodrigoDLPontes/visualization-tool#213]
In the new design for the vistool, the triple bar icon in the upper left is difficult to see in light-mode. Maybe it could be changed to be yellow like the text whilst in light-mode?

<img width="606" alt="Screen Shot 2023-01-31 at 3 02 09 PM" src="https://user-images.githubusercontent.com/51765575/215869958-008d9e3f-c172-41fe-9d96-5afd4a3450e7.png">

**Comment by skapoor68** [comment]
Will look into this. Thank you Ethan for your diligent work and commitment to excellence in CS 1332!

**Comment by ljones315** [comment]
resolved by #216
