### ISSUE TITLE
Kth select superscript formatting 

### ISSUE THREAD

**Issue by iWatger** [RodrigoDLPontes/visualization-tool#231]
The superscript lowercase T in the header of this [window](https://csvistool.com/QuickSelect) kinda look funky in Safari 😳

<img width="440" alt="Screenshot 2023-04-07 at 4 04 21 PM" src="https://user-images.githubusercontent.com/51765575/230672025-eaaac41b-ddb4-490f-8313-5ac780011bc3.png">

**Comment by skapoor68** [comment]
In Chrome too😳
