### ISSUE TITLE
LSDRadix Sort - Step Back Missing Buckets

### ISSUE THREAD

**Issue by iking7** [RodrigoDLPontes/visualization-tool#24]
Hello, I'm having issues skipping back using the LSD radix sort. I tried to add the data: 100, 10, 1. I paused the animation, but I couldn't step back to the beginning. The linked lists did not appear when stepping back. To reproduce this issue, you may add whatever data you please. Once you allow the first iteration of LSD to complete and the data from the buckets are placed back into the array, you are unable to put the data back into the buckets when stepping back. I thank all the TAs who worked on the visualization tool. It has been beneficial to my peers and me.

**Comment by RodrigoDLPontes** [comment]
Hi, thanks for the feedback and support! Could you confirm that the issue is fixed now?

**Comment by iking7** [comment]
Yes, I can confirm the issue has been fixed! Thank you.
