### ISSUE TITLE
Feature request: Choose pivot for QuickSort/QuickSelect

### ISSUE THREAD

**Issue by PranavMahesh1** [RodrigoDLPontes/visualization-tool#25]
It would be great if we could pick our own pivot for each iteration of QuickSort and QuickSelect, so we can visualize it better.

**Comment by RodrigoDLPontes** [comment]
Thanks for the feedback Pranav! Unfortunately, currently there is no way to interact with the animation while it is playing, and implementing so would be non-trivial amount of work (quite a lot, to be honest). It might be possible to encode this in the input, however. I'll add your suggestion to the Projects tab.
