### ISSUE TITLE
Characters that can be inserted are inconsistent across data structures

### ISSUE THREAD

**Issue by luciankt** [RodrigoDLPontes/visualization-tool#280]
For example, ArrayLists allow any alphanumeric character and symbol (including space) to be added, but LinkedLists only allow digits. Similar inconsistencies exist across all of the data structures.

Ideally they should all accept digits ~~and alphabetical characters (unless only numerical values make sense)~~ but not symbols or spaces.

**Comment by skapoor68** [comment]
I think all data structures except HashMaps should be restricted to digit-only input. And for all data structures, all spaces should be trimmed from any inputs. Feel free to make changes for this

**Comment by luciankt** [comment]
Sounds good to me, I wasn't sure if alphabetic characters should be allowed or not.
