### ISSUE TITLE
UI feedback when an invalid index is used

### ISSUE THREAD

**Issue by luciankt** [RodrigoDLPontes/visualization-tool#282]
Currently no text feedback is provided when attempting to add or remove an element at an out-of-bounds index in ArrayList and the three LinkedLists. It would be good if it told the user that the index is out of bounds to prevent confusion as to why no animation plays.

**Comment by skapoor68** [comment]
Yeah this is related to #140. You can do something similar to #249 where the user is given an explanation as to why the animation does not run. It'd be nice if this is accounted for in the remaining visualizations without this feature.
