### ISSUE TITLE
HashMap (Probing): Cannot modify initial capacity

### ISSUE THREAD

**Issue by yumemio** [RodrigoDLPontes/visualization-tool#320]
Hi all!👏 I've found a subtle bug in the HashMap (Probing) page:

## Steps to reproduce

1. Go to [the HashMap (Probing) page](https://csvistool.com/OpenHash).
2. Click the "initial capacity" textbox.
3. Type a numerical value, e.g. 12

## Expected behavior

The typed value is set as the new initial capacity.

## Actual behavior

The textbox is not modifiable, and the capacity does not change.

## Environment

Hardware: Windows 11
Browser: Firefox (121.0), also reproduces on Chrome (120.0.6099.130).

**Comment by luciankt** [comment]
Thank you! [Fixed](https://github.com/RodrigoDLPontes/visualization-tool/commit/d35d35d33400e4f3a547903a35c1854eec95994f).
