### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ML-Chen** [RodrigoDLPontes/visualization-tool#41]
What license do the source code here and the resulting visualizations fall under? Would it be compatible with CC BY-SA 3.0? I'm wondering if it would be okay to reuse the visualizations on Wikipedia. Apparently the David Galles visualization tool code is [licensed under FreeBSD](https://www.cs.usfca.edu/~galles/visualization/).

**Comment by RodrigoDLPontes** [comment]
We have updated the repo with licensing information (you can read the fine print in LICENSE.md). It will continue to use the FreeBSD License. Hope that gives you enough information! If not feel free to open another issue.
