### ISSUE TITLE
BST Levelorder Traversal

### ISSUE THREAD

**Issue by timskovjacobsen** [RodrigoDLPontes/visualization-tool#97]
First of all, thanks for a great tool for visualizing data structures. It is very helpful to solidify the concepts.

When creating a Binary Search Tree with data `15,2,26,1,9,19,30,7,12,17,20,22`, performing a Levelorder Traversal correctly visits the nodes. However, when the entire traversal is completed, the sequence of visited nodes displayed in the bottom left corner of the canvas is not retained.

The other traversal types do retain the returned sequence correctly so it can be viewed after completion.

**Comment by migueldlr** [comment]
Thank you for raising the issue! This should be fixed now!
